spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        ddl-auto: none
        default_schema: ${DB_SCHEMA}
        show_sql: true
        format_sql: true
  liquibase:
    change-log: classpath:/db.changelog/changelog-master.yaml
settings:
  jwt:
    key: liasudhdfliuWSNDKLQWEJasbdkuABSCUYwgdyifQVWYDIFquyfdabsdyhuFTASasujhdkjasuhdqiuwgdhkuyagskdjyhgjuqywgduyafsjhdfahjgfdyqfwyfdqwfdtdaisjhdliquwhkdjbasjdhgasjkdygakjsdhgakjshxjkbasxjkuhbaskuxygqwkudgqkujbdkjahgiuyguiGIUDgyausfdgJHAgfsdhjyFYQAFWDy
    access-token-expectation: 3600000
    refresh-token-expectation: 86400000

logging:
  level:
    org:
      hibernate:
        type: trace

DB_URL: jdbc:postgresql://localhost:5432/walliet
DB_USERNAME: w_admin
DB_PASSWORD: pass123
DB_SCHEMA: w_dev

